export const formInputs = {
  firstName: {
    id: 'firstName',
    type: 'text',
    label: 'First Name',
    placeholder: 'First name (optional)',
    required: false,
    value: '',
  },
  userName: {
    id: 'userName',
    type: 'text',
    label: 'Username',
    placeholder: 'Enter username',
    required: true,
    value: '',
    errorMessage: 'Please enter username',
  },
  password: {
    id: 'password',
    type: 'password',
    label: 'Password',
    placeholder: 'Enter password',
    required: true,
    value: '',
    errorMessage: 'Please enter password',
  },
  repeatPassword: {
    id: 'repeatPassword',
    type: 'password',
    label: 'Repeat password',
    placeholder: 'Repeat password',
    required: true,
    value: '',
    errorMessage: 'Passwords are different',
  },
  email: {
    id: 'email',
    type: 'email',
    label: 'Email',
    placeholder: 'Enter your email',
    required: true,
    value: '',
    errorMessage: 'Email format is incorrect',
  }
};